### ISSUE TITLE
Database URL parsing doesn't support Mongo databases with multiple hosts

### ISSUE THREAD

**Issue by gtelljohann** [pwnall/node-parse-database-url#6] opened 2015-04-06 20:54 UTC
MongoDB has guidelines for specifying multiple hosts in a single database URI (http://docs.mongodb.org/v2.6/reference/connection-string/), but node-parse-database-url doesn't support this.

**Comment by marbemac** [comment] 2015-09-14 04:02
+1

**Comment by pwnall** [comment] 2015-09-25 06:42
How should the multiple hosts be returned? Is there any driver that takes up an options object?

I skimmed the docs of the node driver recommended by mongo, and it only only seems to accept URL strings.
https://github.com/mongodb/node-mongodb-native/

Once I know what the expected results should be, I can make some progress on this.

**Comment by marbemac** [comment] 2015-09-25 19:20
I believe they should just be returned as a comma delimited string:

"host1.com:10576,host2.com:10698"

This is what I pass into the drivers I use, and it works fine. The issue is that passing in to node-parse-database-url a mongo URI with multiple hosts causes unexpected results. I dont think it likes multiple ports, etc, present in the host part of the URI, where it expects there to be one host and one port.

**Comment by marbemac** [comment] 2015-09-25 19:21
An example full URI with multiple hosts that doesn't work with this lib:

```
mongodb://user:pass@host1.com:10576,host2.com:10698/db_name?replicaSet=set-123
```

**Comment by yaring** [comment] 2016-01-04 12:49
+1

**Comment by wzrdtales** [comment] 2016-01-10 11:15
@pwnall You can find the specs here https://docs.mongodb.org/manual/reference/connection-string/

Can we expect that you find time for this or do you need help?

**Comment by pwnall** [comment] 2016-01-10 17:27
Please take a look at the following branch and let me know if things work as expected.
https://github.com/pwnall/node-parse-database-url/tree/fix_mongo

I'd especially look at the new test cases, as they document my understanding of the parameters expected mongo.

If the branch seems OK, I'll cut out a release. If not, please tell me what's missing (ideally, with test cases), and we'll iterate.

@yaring the branch's code is heavily inspired from your PR. I wouldn't have been able to respond so quickly without it, and I'm very grateful you took the time to put it together! I'm super pressed for time these days, so I wrote things in my style instead of offering feedback and iterating on your PR. I hope you're OK with that. The commit adding the new code does credit you but, unfortunately, git commits doesn't handle multiple authors. Please let me know if there's another form of credit that you would like.

**Comment by wzrdtales** [comment] 2016-01-10 17:57
I think you missed the else keyword here https://github.com/pwnall/node-parse-database-url/blob/fix_mongo/lib/parse-database-url.js#L37-L39, without this would be pretty inconsistent compared to your addition some lines later https://github.com/pwnall/node-parse-database-url/blob/fix_mongo/lib/parse-database-url.js#L52.

The changs would work and the response is as expected an configuration object just like for the other supported uris. To what is expected from mongodb is different and depends actually on the driver or toolset you choose.

There is for example on the one side mongoose or the mongodb native driver. The mongodb native driver for example parses the uri on its own https://github.com/mongodb/node-mongodb-native/blob/a38d2e4f6df0794466a66c41b46593ad84746dcd/lib/mongo_client.js#L125, the mongoose on the other side hasn't the same support for this.

But maybe you should first define which goal your module should fullfil:
Provide an output that is expected to be always an configuration object, or provide an output that works with some given toolsets, drivers and so on.

**Comment by yaring** [comment] 2016-01-11 09:40
@pwnall it's fine as long we have the same goal :smiley: the PR looks pretty good to me.

@wzrdtales I think he meant to parse the user and password as always from the old `url` parser and use it later instead using it from the `mongodb-uri` parser as I did.

btw @wzrdtales this change https://github.com/pwnall/node-parse-database-url/blob/fix_mongo/test/parse_cases.json#L130-L143 will probably require change on `db-migrate` because you expect array of string, not array of objects.

**Comment by wzrdtales** [comment] 2016-01-11 09:58
@yaring Yes I know, but not a big deal to add this.

**Comment by yaring** [comment] 2016-01-11 12:02
@wzrdtales @pwnall, do you think we can push the fix?

**Comment by pwnall** [comment] 2016-01-11 18:28
@yaring @wzrdtales I used an array of objects mostly because it just so happens that what comes out of the mongo URI parser matches the `host`/`port` convention that I used in the configuration object for the other databases.

I'm considering adding a `host`/`port` that points to the first server in the comma-separated server list, and I'm considering adding a one-element `hosts` object to the other configuration objects. This would re-unify the configuration object. What do you think?

**Comment by pwnall** [comment] 2016-01-11 18:29
@wzrdtales I'm particularly interested if this would break node-db-migrate.

**Comment by wzrdtales** [comment] 2016-01-11 18:31
@pwnall Could you maybe add an example json here?

**Comment by wzrdtales** [comment] 2016-01-11 18:34
@pwnall I don't think pointing to a single server if there is a **group** of them is not a good behavior and I guess no one would expect this to happen.

**Comment by wzrdtales** [comment] 2016-01-11 18:38
@pwnall And about breaking db-migrate, as long as you don't publish this as a patch this doesn't break db-migrate its included with ~ https://github.com/db-migrate/node-db-migrate/blob/master/package.json#L54

**Comment by pwnall** [comment] 2016-01-11 18:40
@wzrdtales I was thinking the single host/port would be used by drivers that can only connect to one database in the group. Are multiple databases used for replication or for sharding? If it's the latter, I shouldn't add "host"/"port" properties indeed.

**Comment by pwnall** [comment] 2016-01-11 18:41
I updated the branch with the changes I was thinking about.

This change would definitely not go out as a patch, because it changes the output in existing use cases.

**Comment by wzrdtales** [comment] 2016-01-11 18:42
@pwnall In case of mongodb both also see https://docs.mongodb.org/manual/reference/connection-string/ for more informations.

**Comment by wzrdtales** [comment] 2016-01-11 18:44
@pwnall Ok ic https://github.com/pwnall/node-parse-database-url/commit/b59460891ba9269562de502c008d67678324bada#diff-a91623f7e4f667f9e7e7bc631453e645R133 

I think most would rather expect host to an array or to not be existent than pointing to single server if there exists a group.

**Comment by yaring** [comment] 2016-01-11 18:53
@wzrdtales What do you think about using array always (single or group) on Mongo case?

**Comment by wzrdtales** [comment] 2016-01-11 18:56
@yaring I don't think this would be a solution, if it would be me I would treat `hosts` to be an array only  and `host` to be a string **or** an array and highlight this in the documentation.

**Comment by yaring** [comment] 2016-01-11 18:59
@wzrdtales so you mean on case of a single server we'll use `host` as an array and on the case of group we'll use `hosts` as an array?

I don't really like to treat `host` as an array.

**Comment by wzrdtales** [comment] 2016-01-11 19:02
@yaring y and if a singular term can be an array or not really hardly depends on opinions, to be honest I really don't care if it is plural or not, but there shouldn't be a single host definition if there is a group like here https://github.com/pwnall/node-parse-database-url/commit/b59460891ba9269562de502c008d67678324bada#diff-a91623f7e4f667f9e7e7bc631453e645R133, that would potentially cause more trouble then bring good.

**Comment by yaring** [comment] 2016-01-11 19:05
@wzrdtales on that I'm with you, if it's group there shouldn't be a single host definition,
that's why I wanted to have an array always.

**Comment by yaring** [comment] 2016-01-11 19:07
That's what I did on case of group on my PR:
https://github.com/pwnall/node-parse-database-url/pull/7/files#diff-a91623f7e4f667f9e7e7bc631453e645R109

But on my PR on single host I didn't use array which I think now maybe worth to use.

**Comment by pwnall** [comment] 2016-01-11 19:54
Based on your input, I changed the code so that it won't create the `host` / `port` properties on the config object if more than one host is specified. However, I think there's value to having an easy path for drivers that only support one host/port, so I do create the properties if there's a single host.

Also, `mongodb` connections will always have an array at `hosts`. This way, drivers that support multiple connections can always iterate over the array and ignore the `host` / `port` properties.

Does this sound reasonable?

**Comment by wzrdtales** [comment] 2016-01-11 19:58
y, thats ok.

**Comment by pwnall** [comment] 2016-01-11 20:08
I released 0.3.0. Does this solve the mongodb problems?

**Comment by wzrdtales** [comment] 2016-01-11 20:11
From my side this will fix the support of mongodb uris, so yes. Thank you

**Comment by pwnall** [comment] 2016-01-11 20:11
@yaring @wzrdtales Thank you for helping me figure out all the difficult stuff!

**Comment by wzrdtales** [comment] 2016-01-11 20:12
You're welcome!

**Comment by yaring** [comment] 2016-01-11 22:13
No problem :v:

**Comment by kaitoukiddo** [comment] 2016-01-12 03:47
Pig is undressing @pwnall

**Comment by kaitoukiddo** [comment] 2016-01-12 03:48
Pig has an ogasm @pwnall

**Comment by kaitoukiddo** [comment] 2016-01-12 03:49
Cheating King, while your dick is in pig's pussy, you are sending other's messages @pwnall @spark008

**Comment by pwnall** [comment] 2016-01-13 01:36
I'll close this bug for now. Please let me know if the new release doesn't fix things for you!

**Closed by pwnall** 2016-01-13 01:36 UTC
